name = "diploma_lean_2"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["DiplomaLean2"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "DiplomaLean2"
